### ISSUE TITLE
it is not working for me, but why?

### ISSUE THREAD

**Issue by komikcocuk** [kaifcoder/gemini_multipdf_chat#1]
whenever i ask something, it says "This context does not mention anything about signs, symptoms and presentations in emergency medicine field, so I cannot extract the requested data from the provided context."

i think it can't see the pdf's i uploaded. 

But upload process is successfull.

Please help. 

<img width="1876" alt="Screenshot 2024-02-14 211035" src="https://github.com/kaifcoder/gemini_multipdf_chat/assets/153206716/4cee0a50-e550-4897-bb9d-a21dd51c7383">

**Comment by komikcocuk** [comment]
These are pdf's about emergency medicine field and they are containing info about my question. This is the result everytime i tried, with different pdfs.

**Comment by kaifcoder** [comment]
try to rephrase the question and if your pdf contains non ocr text it can't read them then you will get this error
