### ISSUE TITLE
RuntimeError: Error in faiss::FileIOReader::FileIOReader(const char *) at /Users/runner/work/faiss-wheels/faiss-wheels/faiss/faiss/impl/io.cpp:68: Error: 'f' failed: could not open faiss_index/index.faiss for reading: No such file or directory

### ISSUE THREAD

**Issue by maxosorios** [kaifcoder/gemini_multipdf_chat#10]
Hi, I've an error;

RuntimeError: Error in faiss::FileIOReader::FileIOReader(const char *) at /Users/runner/work/faiss-wheels/faiss-wheels/faiss/faiss/impl/io.cpp:68: Error: 'f' failed: could not open faiss_index/index.faiss for reading: No such file or directory

can you help me?

Thxz!

**Comment by kaifcoder** [comment]
please add steps to reproduce this error

**Comment by maxosorios** [comment]
HI kaifcoder, i resolved the issue. Need put the buttom submit & process before introduce a prompt :)

**Comment by maxosorios** [comment]
How can Apply memory in the chat prompt?
