### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'faiss_index'

### ISSUE THREAD

**Issue by CevreMuhendisi** [kaifcoder/gemini_multipdf_chat#5]
I used a Docker image, but it's giving an error. I'm getting the following error

![image](https://github.com/kaifcoder/gemini_multipdf_chat/assets/59526034/be83fe8d-5be5-42c3-b4a0-85b3b20c9e48)

PermissionError: [Errno 13] Permission denied: 'faiss_index'
Traceback:
File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
File "/app/app.py", line 144, in <module>
    main()
File "/app/app.py", line 103, in main
    get_vector_store(text_chunks)
File "/app/app.py", line 44, in get_vector_store
    vector_store.save_local("faiss_index")
File "/usr/local/lib/python3.10/site-packages/langchain_community/vectorstores/faiss.py", line 1078, in save_local
    path.mkdir(exist_ok=True, parents=True)
File "/usr/local/lib/python3.10/pathlib.py", line 1173, in mkdir
    self._accessor.mkdir(self, mode)

**Comment by kaifcoder** [comment]
try to create a folder named faiss_index then re create the container

**Comment by Dribo** [comment]
@CevreMuhendisi 

The user "appuser" does not have ownership of the folder "app", where faiss is attempting to store vectors. I fixed this by adding the following to the dockerfile. The line should be added just after creating the user with the "adduser" command. 

[...]
RUN adduser [...]

# Change the ownership of the /app directory to appuser    
RUN chown appuser:appuser /app                                          <--- This line is the addition

[...]

Simply save the dockerfile, run docker compose again, and it should work as it did for me.

And remember to press "Submit & Process" in the interface ;)

**Comment by kaifcoder** [comment]
@Dribo create a pull request with changes you suggest

**Comment by kaifcoder** [comment]
Issue is resolved
